spring:
    profiles:
        active: @spring.profiles.active@
server:
  servlet:
    context-path: /
  port: 8082

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/codebetterdb
    username: postgres
    password: passwd123
    pool-size: 30

